### ISSUE TITLE
Confidence Values Stuck ?!

### ISSUE THREAD

**Issue by ekinhorzum** [Zillode/OSCeleton-KinectSDK#2]
I may be doing smth wrong (since I am no expert) but confidence values got stuck and it is a nightmare in my case since I am trying to fuse two kinects wrt their confidence values

**Comment by Zillode** [comment]
What do you mean with 'stuck'?
The confidence values are defined as follows:
```
            if (j.TrackingState == JointTrackingState.Tracked) return 1;
            if (j.TrackingState == JointTrackingState.Inferred) return 0.5;
            if (j.TrackingState == JointTrackingState.NotTracked) return 0.1;
            return 0.5;
```

**Comment by ekinhorzum** [comment]
It simply freezes at one of those values for 1-2 seconds. (It may be some other mistake of me as well. I am trying to fuse skeleton data from two kinects and when the confidence value is stuck/frozen the output is also frozen . Previously I had the same frozen output issue with mvm9289/multikinect , so yeah, i may be doing smth wrong elsewhere)

Any recommendations?
