### ISSUE TITLE
Locating OSC data

### ISSUE THREAD

**Issue by nakama1** [Zillode/OSCeleton-KinectSDK#4]
In the main window, spacebar writes gesture to a new file, but we are unable to find the location of that file. Could you help us access the osc data which is being streamed?

**Comment by Zillode** [comment]
It should be stored in your personal [Documents](https://github.com/Zillode/OSCeleton-KinectSDK/blob/d72f8442334cb5ceec08cb114a4f6d7f5fcb71dd/SkeletonBasics-WPF/MainWindow.xaml.cs#L643) folder.
